gateway:
  name: opsmgmt-gateway-03
  namespace: envoy-gateway-system-03

siteinfo:
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: papaginos_app
  db_username: web_user
  web_emdomain:
  - papaginos-em.net-chef.com
  web_ncdomain:
  - papaginos.net-chef.com
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: RISEBRANDS_APP
  db_username: WEB_USER
  web_emdomain:
  - risebrands-em.net-chef.com
  web_ncdomain:
  - risebrands.net-chef.com
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: FRISCHS_APP
  db_username: WEB_USER
  web_emdomain:
  - frischs-em.net-chef.com
  web_ncdomain:
  - frischs.net-chef.com
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: BOPARAN_APP
  db_username: web_user
  web_emdomain:
  - boparan-em.net-chef.com
  web_ncdomain:
  - boparan.net-chef.com
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: QUAKERSTEAK_APP
  db_username: web_user
  web_emdomain:
  - quakersteak-em.net-chef.com
  web_ncdomain:
  - quakersteak.net-chef.com
- db_password_vault_key: PROD_STANDARD
  db_port: '1521'
  db_server: prcl040.prod.crunchtime.it
  db_servicename: TROPICALSMOOTHIECAFE_APP
  db_username: WEB_USER
  web_emdomain:
  - tropicalsmoothiecafe-em.net-chef.com
  web_ncdomain:
  - tropicalsmoothiecafe.net-chef.com
