db_password_vault_key: PROD_STANDARD
db_port: '1521'
db_server: prcl029.prod.crunchtime.it
db_servicename: PHILZCOFFEE_APP
db_username: WEB_USER
web_emdomain:
  - philzcoffee-em.net-chef.com
web_ncdomain:
  - philzcoffee.net-chef.com
disable: true
